server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/conmarred/servicios_config
        default-label: main
       # native:
        #  search-locations:
         # - file:///c:\temp\config
        